defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local


### Offline
offline: False
bc_weight: 2.5
bc: True
offline_data_dir: ???
num_train_steps: 2000000
eval_freq: 1000
### IQL
expectile: 0.7
temperature: 1.0
### CQL
cql_importance_sample: False
temp: 1.0
min_q_weight: 1.0
num_random: 10
with_lagrange: False
lagrange_thresh: 0.0

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 0
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
encoder_lr: 1e-4
feature_dim: 50
exp_name: default
inv: false
reward: true
temporal: false
multistep: 1
lars: false
drqv2: false
spr: false
curl: true
target: ???
### drqv2_offline.DrQV2Agent, bc.BCAgent, cql.CQLAgent, iql.IQLAgent
  
agent:
  _target_: ${target}
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  encoder_lr: ${encoder_lr}
  critic_target_tau: 0.01
  update_every_steps: 1
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: 'linear(1.0,0.1,10000)'
  stddev_clip: 0.3
  inv: ${inv}
  reward: ${reward}
  temporal: ${temporal}
  multistep: ${multistep}
  lars: ${lars}
  #latent_a_dim: ${latent_a_dim}
  drqv2: ${drqv2}
  spr: ${spr}
  curl: ${curl}
  bc: ${bc}
  expectile: ${expectile}
  temperature: ${temperature}
  cql_importance_sample: ${cql_importance_sample}
  temp: ${temp}
  min_q_weight: ${min_q_weight}
  num_random: ${num_random}
  with_lagrange: ${with_lagrange}
  lagrange_thresh: ${lagrange_thresh}

hydra:
  run:
    dir: ./offline_exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm

